export const FETCH_SEARCH_VIN_START = 'FETCH_SEARCH_VIN_START'
export const WRITE_TO_CACHE = 'WRITE_TO_CACHE'
export const UPDATE_VIN = 'UPDATE_VIN'
export const NOT_FIND_INFORMATION = 'NOT_FIND_INFORMATION'
export const FETCH_VIN_FAILURE = 'FETCH_VIN_FAILURE'
export const SET_VIN = 'SET_VIN'

